# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cd1b04316727a4bc92cb3c53d581093c992c8391b9c4199a5d7cdd377b19cf04c5585a11b9ee79f1c38ec9ce3d9fd5bafcd76504516950b2486c831551d25845

test:
  secret_key_base: dfac5aa31109c42a3dc2752fdc3235b1041eeac497f7f6a516149a221cf98c24a3c77a409f4537bc973548deb948bf2470c9fab08f75024dfa9df6af65fc19bc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
